name: ci
on: [ push, pull_request ]


jobs:
  choco:
    name: choco
    runs-on: windows-2022
    continue-on-error: false
    timeout-minutes: 5
    strategy:
      fail-fast: false
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: "`chocolatey` ~ install git"
        run: choco install git.install --params "'/GitAndUnixToolsOnPath /WindowsTerminal /NoAutoCrlf'"

      - name: "`chocolatey` ~ install deps"
        run: choco install mingw cmake

